# 💝 Support goovers Development
# Your support helps maintain and improve these eggs

# 🌟 GitHub Sponsors
github: goover

# 🎨 Creative Platform Support
patreon: oldnoob

# ☕ Coffee & Quick Support
ko_fi: oldnoob
buy_me_a_coffee: goover
liberapay: goover

# 🎯 Developer Appreciation
thanks_dev: "u/gh/goover"

# 🔗 Primary Donation Platform
custom: https://donate.goover.dev

# 📝 Additional platforms (not currently used)
# open_collective: # Replace with Open Collective username
# tidelift: # Replace with Tidelift platform-name/package-name
# community_bridge: # Replace with Community Bridge project-name
# liberapay: # Replace with Liberapay username
# issuehunt: # Replace with IssueHunt username
# lfx_crowdfunding: # Replace with LFX Crowdfunding project-name
# polar: # Replace with Polar username
