name: Merge JSON Files

on:
  push:
    branches:
      - main

jobs:
  merge-json:
    runs-on: ubuntu-latest

    steps:
      - name: 📥 Checkout repository
        uses: actions/checkout@v3

      - name: 🛠 Set up latest Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '22'

      - name: 📦 Install dependencies
        run: npm install glob

      - name: 🧩 Run merge script
        run: node merge-json.js

      - name: ✅ Commit merged.json
        run: |
          git config --global user.name "github-actions"
          git config --global user.email "github-actions@github.com"
          git add merged.json
          git commit -m "Automatisch generierte merged.json mit Metadaten"
          git push